{% set name = "cuda-nsight" %}
{% set version = "12.8.90" %}
{% set cuda_version = "12.8" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set extension = "tar.xz" %}  # [not win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nsight/{{ platform }}/cuda_nsight-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 3bc79396a171b90a40b57ac00df1a8d5cb31783767b2a66351f2bcf163c9aaa6  # [linux64]

build:
  number: 1
  skip: true  # [not linux64]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}

test:
  commands:
    - test -f $PREFIX/bin/nsight_ee_plugins_manage.sh
    - test -d $PREFIX/nsightee_plugins

about:
  home: https://developer.nvidia.com/nsight-eclipse-edition
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: A unified CPU plus GPU IDE for developing CUDA applications
  description: |
    NVIDIA Nsight Eclipse Edition is a unified CPU plus GPU integrated
    development environment (IDE) for developing CUDA applications for
    the x86, POWER and ARM platforms.
  doc_url: https://developer.nvidia.com/nsight-eclipse-edition

extra:
  recipe-maintainers:
    - conda-forge/cuda
